# Uncomment the next line to define a global platform for your projec
use_frameworks!

platform :ios, '14.1'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'shared', :path => '../shared'
#  pod 'shared:core', :path => '../shared/core'
end


